### ISSUE TITLE
Haas Adapter Issue

### ISSUE THREAD

**Issue by xkel** [TrakHound/MTConnect-Agent-For-Haas#1]
The consistent issue I get when trying to run the solution in Visual Studios is a Windows Service Start Failure. To my understanding also I shouldn't be expecting an interface for the adapter assuming it did run. How can I install and run the service?

![wssfailkure](https://user-images.githubusercontent.com/22240889/27197847-d5b66dca-51dd-11e7-8fb2-e16a01ad30d9.png)

**Comment by PatrickRitchie** [comment]
You most likely need to add the 'debug' command line argument for it to run as a console app instead of a service.
